# Generated by Django 5.0.3 on 2024-11-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcenter',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutorialcenter',
            name='discipline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutorialcenter',
            name='phone',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialcenter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
