# Generated by Django 5.0.3 on 2024-11-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tutorialcenter_address_tutorialcenter_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='uploaded_image'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(null=True, upload_to='uploaded_image'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='uploaded_image'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.ImageField(null=True, upload_to='uploaded_image'),
        ),
        migrations.AddField(
            model_name='tutorialcenter',
            name='image',
            field=models.ImageField(null=True, upload_to='uploaded_image'),
        ),
    ]
