# Generated by Django 5.0.3 on 2024-11-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_image_department_image_student_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcenter',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
