# Generated by Django 5.0.3 on 2024-11-02 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='main.course'),
        ),
        migrations.AlterField(
            model_name='tutorialcenter',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
