# Generated by Django 5.0.3 on 2024-11-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_phone_tutor_phone_tutor_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='speciality',
        ),
        migrations.AddField(
            model_name='tutor',
            name='speciality',
            field=models.ManyToManyField(null=True, related_name='tutors', to='main.course'),
        ),
    ]
