# Generated by Django 5.0.3 on 2024-11-04 22:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_tutor_speciality_tutor_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='tutorial_center',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorialcenter',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tutorial_center',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_approved',
        ),
        migrations.CreateModel(
            name='CBTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question for the CBT')),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_questions', to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('year', models.CharField(help_text='Year of the examination', max_length=4)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_questions', to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='KeyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Key points or brief answers related to past questions')),
                ('past_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='main.pastquestions')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeExplanations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', ckeditor.fields.RichTextField(help_text='Explanation for the correct answer in CBT')),
                ('cbt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='main.cbtquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='TutorialCenter',
        ),
    ]
