# Generated by Django 5.0.3 on 2024-11-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_remove_student_school_remove_teacher_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tutorialcenter',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='tutorialcenter',
            name='phone',
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKKOdmJz8Z2pDtYgFgR2u9spABvNNPKYYtGw&s', max_length=5000, null=True, upload_to='uploaded_image'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKKOdmJz8Z2pDtYgFgR2u9spABvNNPKYYtGw&s', null=True, upload_to='uploaded_image'),
        ),
        migrations.AlterField(
            model_name='tutorialcenter',
            name='image',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKKOdmJz8Z2pDtYgFgR2u9spABvNNPKYYtGw&s', null=True, upload_to='uploaded_image'),
        ),
    ]
