# Generated by Django 5.0.3 on 2024-11-26 14:12

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_remove_course_percentage_usercourseprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestions',
            name='course',
        ),
        migrations.RemoveField(
            model_name='theorysubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='theorysubmission',
            name='user',
        ),
        migrations.CreateModel(
            name='PastQuestionsObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor.fields.RichTextField(help_text='CBT question')),
                ('option_a', models.CharField(blank=True, help_text='Option A (leave blank for theory)', max_length=200, null=True)),
                ('option_b', models.CharField(blank=True, help_text='Option B (leave blank for theory)', max_length=200, null=True)),
                ('option_c', models.CharField(blank=True, help_text='Option C (leave blank for theory)', max_length=200, null=True)),
                ('option_d', models.CharField(blank=True, help_text='Option D (leave blank for theory)', max_length=200, null=True)),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Correct option (leave blank for theory)', max_length=1, null=True)),
                ('year', models.CharField(help_text='Year of the examination', max_length=4)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_questions', to='webapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='ObjGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score', max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique submission ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_grades', to='webapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_grades', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_grades', to='webapp.pastquestionsobj')),
            ],
        ),
        migrations.AlterField(
            model_name='keypoints',
            name='past_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='webapp.pastquestionsobj'),
        ),
        migrations.AlterField(
            model_name='practiceexplanations',
            name='cbt_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='webapp.pastquestionsobj'),
        ),
        migrations.CreateModel(
            name='PastQuestionsTheory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor.fields.RichTextField(help_text='Theory question')),
                ('response', ckeditor.fields.RichTextField(help_text="User's response")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded', models.BooleanField(default=False, help_text='Grading status')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Grade', max_digits=5, null=True)),
                ('feedback', ckeditor.fields.RichTextField(blank=True, help_text='Optional feedback')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_questions', to='webapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score', max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique submission ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theory_grades', to='webapp.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_grades', to='webapp.pastquestionstheory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_grades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='TheorySubmission',
        ),
        migrations.DeleteModel(
            name='PastQuestions',
        ),
    ]
