# Generated by Django 5.0.3 on 2024-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_remove_pastquestions_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestionstheory',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='pastquestionstheory',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='pastquestionstheory',
            name='graded',
        ),
        migrations.RemoveField(
            model_name='pastquestionstheory',
            name='response',
        ),
        migrations.RemoveField(
            model_name='pastquestionstheory',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='pastquestionsobj',
            name='body',
            field=models.CharField(help_text='Waec / Jamb?', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pastquestionstheory',
            name='body',
            field=models.CharField(help_text='Waec / Jamb?', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pastquestionstheory',
            name='year',
            field=models.CharField(help_text='Year of the examination', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pastquestionsobj',
            name='year',
            field=models.CharField(help_text='Year of the examination', max_length=4, null=True),
        ),
    ]
