# Generated by Django 5.0.3 on 2024-11-26 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_remove_pastquestionstheory_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorygrade',
            name='response',
            field=ckeditor.fields.RichTextField(help_text="Student's response", null=True),
        ),
    ]
