# Generated by Django 5.0.3 on 2024-11-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_theorygrade_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='speciality',
        ),
        migrations.AlterField(
            model_name='theorygrade',
            name='score',
            field=models.DecimalField(decimal_places=2, help_text='Score', max_digits=5, null=True),
        ),
    ]
