# Generated by Django 5.0.3 on 2024-11-28 09:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_remove_tutor_speciality_alter_theorygrade_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestionstheory',
            name='body',
        ),
        migrations.AddField(
            model_name='theorygrade',
            name='question_text',
            field=ckeditor.fields.RichTextField(help_text='Theory question', null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='webapp.course'),
        ),
    ]
