# Generated by Django 5.0.3 on 2024-11-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_remove_pastquestionstheory_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
