# Generated by Django 5.0.3 on 2024-11-28 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_course_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorygrade',
            name='note',
            field=ckeditor.fields.RichTextField(help_text='Note for Student', null=True),
        ),
    ]
