# Generated by Django 5.0.3 on 2024-11-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_theorygrade_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorygrade',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Score Over 100', max_digits=5, null=True),
        ),
    ]
