# Generated by Django 5.0.3 on 2024-11-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_alter_theorygrade_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theorygrade',
            name='question_text',
        ),
    ]
