# Generated by Django 5.0.3 on 2024-11-29 14:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_remove_theorygrade_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorygrade',
            name='question_text',
            field=ckeditor.fields.RichTextField(help_text='Theory question', null=True),
        ),
    ]
