# Generated by Django 5.0.3 on 2024-12-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_theorygrade_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='phone',
        ),
    ]
