# Generated by Django 5.0.3 on 2024-12-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_alter_topic_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='speciality',
        ),
        migrations.AddField(
            model_name='tutor',
            name='speciality',
            field=models.ManyToManyField(null=True, related_name='speciality', to='webapp.course'),
        ),
    ]
