# Generated by Django 5.0.3 on 2024-12-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_alter_pastquestionstheory_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorygrade',
            name='image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='uploaded_image'),
        ),
    ]
