# Generated by Django 5.0.3 on 2024-12-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_achievement_userachievement_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_topics',
            field=models.ManyToManyField(blank=True, related_name='users_completed', to='webapp.topic'),
        ),
    ]
