# Generated by Django 5.0.3 on 2024-12-18 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_discussionforum_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionforum',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='webapp.course'),
        ),
    ]
