# Generated by Django 5.0.3 on 2024-12-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_discussionforum_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='login_streak',
        ),
    ]
