# Generated by Django 5.0.3 on 2024-12-21 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_uploadedimagecustom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquestionresponse',
            name='student',
            field=models.ForeignKey(help_text='The student who submitted the response.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
