# Generated by Django 5.0.3 on 2024-12-21 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0057_alter_customquestionresponse_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquestion',
            name='tutor',
            field=models.ForeignKey(help_text='The user who created this question.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
