# Generated by Django 5.0.3 on 2024-12-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0060_remove_customquestion_creator_customquestion_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquestionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='customquestionresponse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='uploadedimagecustom',
            name='custom_grade',
        ),
        migrations.DeleteModel(
            name='CustomQuestion',
        ),
        migrations.DeleteModel(
            name='CustomQuestionResponse',
        ),
        migrations.DeleteModel(
            name='UploadedImageCustom',
        ),
    ]
