# Generated by Django 5.0.3 on 2024-12-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0064_tutorialcenter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
