# Generated by Django 5.0.3 on 2025-01-03 00:16

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0066_discussionforum_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the custom topic.', max_length=255, null=True)),
                ('contents', ckeditor.fields.RichTextField(help_text='Enter the topic contents in rich text format.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the topic was created.')),
                ('center', models.CharField(blank=True, help_text='The institution or center creating this topic.', max_length=255, null=True)),
                ('course', models.ForeignKey(help_text='The course this topic belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_topics', to='webapp.course')),
                ('creator', models.ForeignKey(help_text='The tutor or institution who created this topic.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
